---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soundoff-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soundoff-controller
  template:
    metadata:
      labels:
        app: soundoff-controller
    spec:
      containers:
        - name: controller
          image: ghcr.io/glizzus/soundoff/soundoff-controller:1032a906b5450877af957edda4a1a093b0e20001
          envFrom:
            - configMapRef:
                name: soundoff-config
          env:
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: soundoff-minio-secret
                  key: MINIO_ROOT_PASSWORD
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: soundoff-redis-secret
                  key: REDIS_ADDR
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: soundoff-discord-secret
                  key: DISCORD_TOKEN
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: soundoff-db-secret
                  key: PGPASSWORD
        - image: ghcr.io/glizzus/soundoff/soundoff-worker:1032a906b5450877af957edda4a1a093b0e20001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soundoff-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soundoff-worker
  template:
    metadata:
      labels:
        app: soundoff-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/glizzus/soundoff/soundoff-controller:1032a906b5450877af957edda4a1a093b0e20001
          envFrom:
            - configMapRef:
                name: soundoff-config
          env:
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: soundoff-minio-secret
                  key: MINIO_ROOT_PASSWORD
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: soundoff-redis-secret
                  key: REDIS_ADDR
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: soundoff-discord-secret
                  key: DISCORD_TOKEN
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: soundoff-db-secret
                  key: PGPASSWORD
        - image: ghcr.io/glizzus/soundoff/soundoff-worker:1032a906b5450877af957edda4a1a093b0e20001
