services:
  dev:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ../:/workspaces
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: soundoff
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  minio-data:
  redis-data: