- name: Infrastructure Hosts
  vars_files:
    - secrets.yaml
  hosts: infra
  tasks:
    - name: Add Docker GPG key
      ansible.builtin.rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable/
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/fedora/gpg
        enabled: true

    - name: Install Docker packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    - name: Ensure Docker service is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Create /opt/infra directory
      ansible.builtin.file:
        path: /opt/infra
        state: directory
        mode: '0755'

    - name: Copy docker-compose file to /opt/infra
      ansible.builtin.copy:
        src: docker-compose.yaml
        dest: /opt/infra/docker-compose.yaml
        mode: '0644'
      notify: Run docker-compose

    - name: Run docker-compose
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /opt/infra
      register: compose_output
      changed_when: "'Creating' in compose_output.stdout or 'Starting' in compose_output.stdout"
      environment:
        REDIS_PASSWORD: "{{ redis_password }}"
        MINIO_ROOT_PASSWORD: "{{ minio_root_password }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
