name: CI Pipeline
on:
  push:
    branches:
      - main
    paths-ignore:
      - deploy/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./...

      - name: Build Docker images
        run: docker compose -f ci/docker-compose.build.yaml build

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker images
        run: docker compose -f ci/docker-compose.build.yaml push

      - name: Install yq
        run: go install github.com/mikefarah/yq/v4@latest

      - name: Update deployment manifests
        run: |
          yq eval -i '.spec.template.spec.containers[0].image = "ghcr.io/glizzus/soundoff/soundoff-controller:${{ github.sha }}"' deploy/controller-deployment.yaml
          yq eval -i '.spec.template.spec.containers[0].image = "ghcr.io/glizzus/soundoff/soundoff-worker:${{ github.sha }}"' deploy/worker-deployment.yaml

      - name: Commit changes back to repo
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add deploy
          git commit -m "Update deployment manifests"
          git push
